# --- CONFIGURATION DE BASE ---
baseURL = "https://wheelr00t.github.io/wheelroot/"
title = "Wheelr00t - Blog Cyber"
theme = "LoveIt"

# --- CONFIGURATION DE LANGUE ---
defaultContentLanguage = "fr"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false

[languages]
  [languages.fr]
    weight = 1
    title = "Wheelr00t - Blog Cyber"
    languageCode = "fr-fr"

# --- PARAMS ---
[params]
  # LoveIt version
  version = "0.2.X"
  description = "Description de mon blog cyber"
  
  # Auteur
  [params.author]
    name = "Wheelr00t"
  
  # Header
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "Wheelr00t Blog"
      pre = "<i class='fas fa-terminal'></i>"
  
  # Home page
  [params.home]
    [params.home.profile]
      enable = true
      title = "Wheelr00t Blog"
      subtitle = "Write-ups et cybersécurité"
    [params.home.posts]
      enable = true

  # Page settings
  [params.page]
    [params.page.toc]
      enable = true
    [params.page.code]
      copy = true
      maxShownLines = 50

# --- MENUS ---
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "À Propos"
    url = "/about/"
    weight = 3

# --- TAXONOMIES ---
[taxonomies]
  category = "categories"
  tag = "tags"

# --- OUTPUTS ---
[outputs]
  home = ["HTML", "RSS", "JSON"]

# --- MARKUP ---
[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    lineNumbersInTable = true
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true
