# --- CONFIGURATION DE BASE ---
baseURL = "https://wheelr00t.github.io/wheelroot/" # VÉRIFIE CETTE URL !
languageCode = "fr-fr"
title = "Mon Blog Cyber" # METS TON VRAI TITRE
theme = "LoveIt"

# --- PARAMS (avec corrections) ---
[params]
  # -- Correction pour Erreur 1 (seo.html) --
  # 'author' doit être une table (objet) avec une clé 'name'
  [params.author]
    name = "Wheelr00t" # METS TON NOM/PSEUDO ICI

  description = "Description de mon blog cyber" # METS TA DESCRIPTION

  # -- Ajout pour aider avec Erreur 2 (header.html) --
  # Définir la structure attendue pour le titre dans l'en-tête
  [params.header.title]
    # Tu peux mettre un logo plus tard ici si tu veux
    # logo = "/images/logo.png"
    name = "Wheelr00t Blog" # METS LE TEXTE VOULU POUR L'ENTETE

# --- Active les taxonomies de base ---
[taxonomies]
  category = "categories"
  tag = "tags"

# --- MINIMUM pour la recherche intégrée de LoveIt ---
[outputs]
  home = ["HTML", "RSS", "JSON"] # Nécessaire pour la recherche

# --- Options de rendu (peuvent aider à éviter d'autres erreurs) ---
[markup]
  [markup.highlight]
    noClasses = false # Important pour LoveIt
  [markup.goldmark.renderer]
    unsafe = true # Permet HTML brut dans Markdown si besoin
