# --- CONFIGURATION DE BASE ---
baseURL = "https://wheelr00t.github.io/wheelroot/" # VÉRIFIE ENCORE CETTE URL !
title = "Wheelr00t - Blog Cyber" # METS TON VRAI TITRE
theme = "LoveIt"
# Définir explicitement la langue par défaut (même s'il n'y en a qu'une)
defaultContentLanguage = "fr"
# Désactiver explicitement les langues CJK si non utilisées (thèmes vérifient parfois)
hasCJKLanguage = false

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false

[languages]
  [languages.fr]
    weight = 1
    title = "Mes Write-ups de Cybersécurité"
    languageCode = "fr-fr"
    # Les paramètres suivants sont hérités du niveau racine ([params])
    # mais on pourrait les surcharger ici si besoin pour une langue spécifique.
    # title = "Mon Titre en Français"
    # [languages.fr.params]
    #  description = "Description en Français"

# --- PARAMS ---
[params]
  # Auteur (structure correcte)
  [params.author]
    name = "Wheelr00t" # METS TON NOM/PSEUDO

  description = "Description de mon blog cyber" # METS TA DESCRIPTION

  # Header (structure plus complète)
  [params.header]
    desktopMode = "fixed" # ou "normal", "auto"
    mobileMode = "auto" # ou "normal", "fixed"
    [params.header.title]
      # logo = "" # Si tu as un logo
      name = "Wheelr00t Blog" # Texte affiché en haut
      # pre = ""
      # post = ""

# --- MENUS (Ajout d'une section minimale valide) ---
[menu]
  # Décommente et adapte ces lignes quand tu auras du contenu
  # [[menu.main]]
  #   identifier = "posts"
  #   name = "Articles"
  #   url = "/posts/"
  #   weight = 1
  # [[menu.main]]
  #   identifier = "about"
  #   name = "À Propos"
  #   url = "/about/"
  #   weight = 2

# --- TAXONOMIES ---
[taxonomies]
  category = "categories"
  tag = "tags"

# --- OUTPUTS ---
[outputs]
  home = ["HTML", "RSS", "JSON"]

# --- MARKUP ---
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
